### ISSUE TITLE
What type of key?

### ISSUE THREAD

**Issue by chebotar** [mozilla/wp-web-push#111]
Server keys or Browser keys should be used on GCM API Key ?

**Comment by marco-c** [comment]
Hello @chebotar, I've updated the URL to link to a more detailed description of the steps, but I haven't released the new version of the plugin yet.
The URL is: https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-04

In short, the browser key!

**Comment by chebotar** [comment]
I used browser key, what shell I do more? It's not working on my web project. How I can test it?

**Comment by marco-c** [comment]
Is it working in Firefox?
Have you set both the GCM API key and the Sender ID (which is the Project Number)?
Have you followed all the steps outlined in https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-04?

Do you have a public URL that I can see to debug the problem? (I don't need access to the admin, just the public site).

**Comment by chebotar** [comment]
I test it in Chrome. Yes, I set both the GCM API key and the Sender ID and followed all the steps.
Project - http://chpsaratov.ru

**Comment by marco-c** [comment]
Can you test it in Firefox as well?

**Comment by marco-c** [comment]
Ah, your site is served via HTTP. To support Web Push you need to serve your site via HTTPS.

**Comment by chebotar** [comment]
Oh, Thank you :)

**Comment by chebotar** [comment]
Can you debug now? 
https://chpsaratov.ru/

**Comment by marco-c** [comment]
How are you configuring SSL?
Looks like `home_url` in your WordPress installation returns `http://chpsaratov.ru`, so some of the links are still HTTP.
For example, here's an excerpt from your page:

``` HTML
<script type='text/javascript'>
/* <![CDATA[ */
var ServiceWorker = {"url":"http:\/\/chpsaratov.ru\/?webpush_file=worker","register_url":"https:\/\/chpsaratov.ru\/wp-admin\/admin-ajax.php","min_visits":"0","welcome_enabled":"","welcome_title":"\u0427\u041f \u0421\u0430\u0440\u0430\u0442\u043e\u0432","welcome_body":"Successfully subscribed to notifications","welcome_icon":"","subscription_button":"","notification_enabled_icon":"https:\/\/chpsaratov.ru\/wp-content\/plugins\/web-push\/lib\/bell.svg","notification_disabled_icon":"https:\/\/chpsaratov.ru\/wp-content\/plugins\/web-push\/lib\/bell_disabled.svg","prompt_interval":"3","subscription_hint":"Welcome! Use this button to subscribe to notifications.","unsubscription_hint":"You can unsubscribe whenever you want using this button."};
/* ]]> */
</script>
<script type='text/javascript' src='https://chpsaratov.ru/wp-content/plugins/web-push/lib/js/sw-manager.js?ver=4.4.2'></script>
<link rel='https://api.w.org/' href='http://chpsaratov.ru/wp-json/' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://chpsaratov.ru/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://chpsaratov.ru/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 4.4.2" />
<script type="text/javascript">
    jQuery(document).ready(function($){
    $('.calendar-archives').archivesCW();
});
</script><link rel="manifest" href="http://chpsaratov.ru/?webappmanifest_file=manifest">
```

**Comment by marco-c** [comment]
Probably an issue similar to the one described here: http://snippets.webaware.com.au/snippets/wordpress-is_ssl-doesnt-work-behind-some-load-balancers/

**Comment by chebotar** [comment]
Ok, I review this

**Comment by marco-c** [comment]
Can you try to modify the plugin manually? I'd like to test something.

In wp-web-push-main.php, change the line `'url' => home_url('/') . '?webpush_file=worker',` to `'url' => home_url('/', 'https') . '?webpush_file=worker',`.

**Comment by chebotar** [comment]
Check out

**Comment by marco-c** [comment]
Sorry, also another modification, in vendor/marco-c/wp-web-app-manifest-generator/WebAppManifestGenerator.php, change `echo '<link rel="manifest" href="' . home_url('/') . '?webappmanifest_file=manifest">'` to `echo '<link rel="manifest" href="' . home_url('/', 'https') . '?webappmanifest_file=manifest">'`.

**Comment by chebotar** [comment]
Done

**Comment by marco-c** [comment]
Looks like it's working now.
Firefox
![firefox](https://cloud.githubusercontent.com/assets/1616846/12919241/1cda6a16-cf3b-11e5-8d1a-8a74263a80e6.png)

Chromium
![chromium](https://cloud.githubusercontent.com/assets/1616846/12919242/2012b49a-cf3b-11e5-99db-8a4cc51d7c43.png)

**Comment by marco-c** [comment]
Thank you for your help in debugging the issue!
I'll try to update the plugin to include those modifications.

**Comment by chebotar** [comment]
Thank you! It's ok.

**Comment by marco-c** [comment]
I've just released a new version of the plugin that contains these changes.
