### ISSUE TITLE
Failed opening required '/var/www/html/wp-content/plugins/wp-web-push/WebAppManifestGenerator.php' 

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wp-web-push#132]
After I updated https://github.com/mykmelez/wordpress-pwa to the tip of wp-web-push (currently https://github.com/mozilla/wp-web-push/commit/ac08651973efbca152c2a533734a9f6178caf107), all page loads failed with:

> Warning: require_once(/var/www/html/wp-content/plugins/wp-web-push/WebAppManifestGenerator.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/wp-web-push/wp-web-push-main.php on line 5
> Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/plugins/wp-web-push/WebAppManifestGenerator.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/wp-web-push/wp-web-push-main.php on line 5

**Comment by marco-c** [comment]
There's a build step now, running `make build` will generate a `wp-web-push.zip` file containing the plugin.

**Comment by marco-c** [comment]
Opened https://github.com/mykmelez/wordpress-pwa/issues/2.
