### ISSUE TITLE
Automatically tag releases when running `make release`

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wp-web-push#133]
After experiencing #132, I decided to downgrade wordpress-pwa to the latest release of this plugin, but there isn't a tag to identify it. I eventually discovered that 5f29a5449c5d9d5931ac7f9e4ccd63caf69b507f has the description "Version 0.0.3", so presumably that's the revision from which 0.0.3 was released. But it'd be handy to have version tags on each release (and perhaps a "latest" tag to identify the latest release).

**Comment by marco-c** [comment]
I will tag the next releases, I'll keep this issue open to investigate if I can make tagging part of the `release` Makefile target.

**Comment by marco-c** [comment]
With #136, I've created https://github.com/mozilla/wp-web-push/releases/tag/0.0.4.
