### ISSUE TITLE
Option 'Push it' or 'Do not Push'

### ISSUE THREAD

**Issue by chebotar** [mozilla/wp-web-push#141]
Add option 'Push it' on post editor page. It will be checked on default meaning web push is active. If checkbox is not selected – no push after publish.

**Comment by marco-c** [comment]
Great idea. I'll try to implement it in the following days.

**Comment by marco-c** [comment]
Done, and released a new version of the plugin.

**Comment by chebotar** [comment]
Thank you! Nice
