### ISSUE TITLE
Logo graphic uses Open Sans type

### ISSUE THREAD

**Issue by potch** [mozilla/wp-web-push#156]
If you view https://github.com/mozilla/wp-web-push/blob/master/assets/icon.svg on a system without Open Sans installed, it looks like this:

<img width="139" alt="screenshot 2016-02-19 10 02 18" src="https://cloud.githubusercontent.com/assets/253470/13184306/e114aeda-d6ef-11e5-86ad-4d034e3c306a.png">

You'll need to convert the text to outlines instead of &lt;text> for it to render properly.

**Comment by marco-c** [comment]
http://plugins.trac.wordpress.org/changeset/1363673
