### ISSUE TITLE
"AbortError: Error retrieving push subscription" in firefox 46 but works in firefox 44

### ISSUE THREAD

**Issue by wfwalker** [mozilla/wp-web-push#157]
STR:
1. visit https://testmozilla.wpengine.com/web-push/ from firefox 46
2. click on bell

Expected:
1. offer to opt-in to push

Actual:
1. nothing visible. error in console.

NOTE: works in Firefox 44.

**Comment by mykmelez** [comment]
I'm unable to reproduce with the latest nightly build of 46 (Developer Edition) on Mac, using a new profile. After clicking on the bell, I'm prompted to opt in. And once I opt in, I receive the confirmation notification.

**Comment by wfwalker** [comment]
Looking at browser console reveals the following:

`IndexedDB UnknownErr: ActorsParent.cpp:592 <unknown>`
`UnknownError`

**Comment by marco-c** [comment]
This looks like a Firefox bug.

**Comment by wfwalker** [comment]
I tried with subscribing with a fresh profile in 46 and it worked fine. So, something is wrong with my profile.

**Comment by wfwalker** [comment]
Further examination of browser console reveals

> NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "pushManager._window is null" {file: "jar:file:///Applications/FirefoxAurora.app/Contents/Resources/omni.ja!/components/Push.js" line: 194}]'[JavaScript Error: "pushManager._window is null" {file: "jar:file:///Applications/FirefoxAurora.app/Contents/Resources/omni.ja!/components/Push.js" line: 194}]' when calling method: [nsIPushSubscriptionCallback::onPushSubscription]

and

> NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface]

**Comment by mykmelez** [comment]
@wfwalker Grab a debug build from https://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-aurora-macosx64-debug/ (select the bottom-most numbered directory to get the newest build, but _don't_ select the _latest_ directory, which isn't being updated). Install and run it from a terminal. Then see if you get this additional error message in the terminal:

https://dxr.mozilla.org/mozilla-central/rev/d5daf10d3b74b04e8fa63c4e5429de8a0adf79f8/dom/indexedDB/ActorsParent.cpp#582-587

Offhand, my first suspicion is a variant of https://bugzilla.mozilla.org/show_bug.cgi?id=1092090, but I tried loading the page in Nightly, then loading it again in Developer Edition on the same profile, and I still wasn't able to reproduce (it's possible that I didn't go far enough in Nightly first, however). Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1143003.

**Comment by mykmelez** [comment]
> NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "pushManager._window is null" {file: "jar:file:///Applications/FirefoxAurora.app/Contents/Resources/omni.ja!/components/Push.js" line: 194}]'[JavaScript Error: "pushManager._window is null" {file: "jar:file:///Applications/FirefoxAurora.app/Contents/Resources/omni.ja!/components/Push.js" line: 194}]' when calling method: [nsIPushSubscriptionCallback::onPushSubscription]

Ironically, this is an error with an attempt to report the error in the title of this issue!

https://dxr.mozilla.org/mozilla-central/rev/d5daf10d3b74b04e8fa63c4e5429de8a0adf79f8/dom/push/Push.js#194-197

> NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface]

This is a pretty generic failure to retrieve an interface of an XPCOM component; hard to diagnose.

**Comment by ghost** [comment]
> Ironically, this is an error with an attempt to report the error in the title of this issue!

Ouch. I don't think there's much we can do at that point to recover (since it looks like the window has gone away). Do you only get that error when you close the tab, or even if it's open?

I wonder if the IndexedDB error is related. It might throw when we try to persist the subscription (or check for an existing one), and cause the IDB request to hang indefinitely.

**Comment by marco-c** [comment]
@kitcambridge is there more info @wfwalker could give to help debugging the issue? If there is, @wfwalker can you open a bug on bugzilla?
