### ISSUE TITLE
Subscription frontend proposal

### ISSUE THREAD

**Issue by digitarald** [mozilla/wp-web-push#199]
# Initial state

![1 1 initial](https://cloud.githubusercontent.com/assets/8599/13464898/0c00a5d4-e048-11e5-8ff0-334965c1afb3.png)
## Interacted state

_As a user I don't want to be bothered by an omnipresent sticky icon that I don't use._ After the user clicked once and started the permission request.
![1 2 interacted](https://cloud.githubusercontent.com/assets/8599/13464900/0c058838-e048-11e5-840a-8bcfeadb0fde.png)
## Welcome Tooltip

_As a user I want to be aware that I can subscribe and what that bell icon should be._ This tooltip that pops up with some timeout after the page loaded.
![1 3 welcome tooltip](https://cloud.githubusercontent.com/assets/8599/13464899/0c0574b0-e048-11e5-945d-7c21a0dd33f8.png)
# Subscribe
## Tooltip style (desktop)

Tooltip appears when hovering the sticky icon to explain what happens on click.
![2 1a subscribe tooltip](https://cloud.githubusercontent.com/assets/8599/13464901/0c05da36-e048-11e5-85db-77f986d9dca4.png)
## Dialog style (mobile)

Uses the Material design dialog style that slides in and fades out the background. This should give us a more coherent interaction.
![2 1b subscribe overlay](https://cloud.githubusercontent.com/assets/8599/13464902/0c088d1c-e048-11e5-87d1-bceff76f1573.png)
## Confirmation

Cheering the user!
![2 3 subscribe confirmation](https://cloud.githubusercontent.com/assets/8599/13464903/0c0c45b0-e048-11e5-8837-f4cff9aed72b.png)
# Unsubscribe
## Tooltip (desktop)

![3 1a unsubscribe prompt](https://cloud.githubusercontent.com/assets/8599/13464904/0c12208e-e048-11e5-9930-b75f65bad605.png)
## Dialog (Mobile)

![3 1b unsubscribe overlay](https://cloud.githubusercontent.com/assets/8599/13464906/0c16ffd2-e048-11e5-88dc-762ab6e02105.png)
## Confirmation

Bye!
![3 2 unsubscribe confirmation](https://cloud.githubusercontent.com/assets/8599/13464905/0c16139c-e048-11e5-82fd-c35caf822ed9.png)
# Assets

![Bell Icon](https://dl.dropboxusercontent.com/u/1864007/design/wp-push/bell.png)
[@1x](https://dl.dropboxusercontent.com/u/1864007/design/wp-push/bell.png) [@2x](https://dl.dropboxusercontent.com/u/1864007/design/wp-push/bell@2x.png) [svg](https://dl.dropboxusercontent.com/u/1864007/design/wp-push/bell.svg)

![Notification](https://dl.dropboxusercontent.com/u/1864007/design/wp-push/notification.png)
[@1x](https://dl.dropboxusercontent.com/u/1864007/design/wp-push/notification.png) [@2x](https://dl.dropboxusercontent.com/u/1864007/design/wp-push/notification@2x.png) [svg](https://dl.dropboxusercontent.com/u/1864007/design/wp-push/notification.svg)

**Comment by marco-c** [comment]
Where does the bell icon come from? (I need to add it to the credits in the README)

**Comment by marco-c** [comment]
Where does the bell icon come from? (I need to add it to the credits in the README)

**Comment by digitarald** [comment]
Bell reference to get license and author: https://thenounproject.com/search/?q=Bell&i=10289

**Comment by marco-c** [comment]
Ah, I didn't notice it's the same bell of the plugin's icon!

**Comment by digitarald** [comment]
True, I also forgot that :D

**Comment by marco-c** [comment]
@digitarald a question about the interacted vs non-interacted state. The icon gets small and transparent after the user interacts with it, when does it become big again?

**Comment by digitarald** [comment]
@marco-c just thinking loud here: For most users that confirm or deny the prompt it would stay in background. The only special case I can see is a soft-deny, after which the icon should be in faded state for x days, when it re-prompts the user; which we might have as an option in the admin panel.

Would love to hear your thoughts as you have a better understanding of the previous flow.

**Comment by marco-c** [comment]
@digitarald sounds good to me. Should it also return to the default state on hover (and return to the interacted state after you move your mouse out)? (trying to understand why it's in the default state in your proposal images, since in those states the user has certainly already interacted)

**Comment by marco-c** [comment]
Fixed by #209 and #215.
