### ISSUE TITLE
Better match font and white space from mock ups (#199)

### ISSUE THREAD

**Issue by digitarald** [mozilla/wp-web-push#233]
Both the tooltip and the dialog style need some tweaking to align text with images and keep consistent white space. The buttons also need some tweaking on mobile.

**Comment by marco-c** [comment]
Landed some fixes:
54c6c3600feea69c1b5c9c49e6ae13af35ea665f
0a3ecc6ef4c17b179a81d881e3c63ff4608fad04
6b1eea26400b53965f07172863866160ac0f0b0a
58206d5d5e1ea9ae05695340f606c778e9e0b271
133cbd8c31aaa280790d32271789b363ade6a3c5

**Comment by marco-c** [comment]
And:
#235

**Comment by marco-c** [comment]
Some things have been fixed, can you open individual issues for other problems?
