### ISSUE TITLE
Php web app with database

### ISSUE THREAD

**Issue by 15r** [mozilla/wp-web-push#243]
Can your team provide us a php web of (wp-web-push)
It will be so helpful

**Comment by marco-c** [comment]
Hello @15r, can you clarify your request? Do you want to see an example website where `wp-web-push` is installed? Here's one: https://wadi-pwa.sloppy.zone/.

**Comment by 15r** [comment]
@marco-c sir,  I looking for separate web app (website) not an wordpress plugin.
Kindly help me with-it.

**Comment by marco-c** [comment]
This repository contains the source code of a WordPress plugin.

If you're looking for documentation on how to use the Push API, I suggest you look at the documentation on MDN (https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API) or at the examples on the ServiceWorker Cookbook (https://serviceworke.rs/push-simple.html).

**Comment by 15r** [comment]
Thanks for the help @marco-c
