### ISSUE TITLE
Syntax error in the bell.svg file

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wp-web-push#266]
After updating wordpress-pwa to the latest version of wp-web-push and recreating local Docker containers based on the updated image, going to Plugins and pressing activate for the plugin displays a page with this error message:

```
Parse error: syntax error, unexpected 'version' (T_STRING) in /var/www/html/wp-content/plugins/wp-web-push/lib/bell.svg on line 1
```

Returning to the Plugins page shows that the plugin is nevertheless activated. But then going to its Settings page results in the Push Triggers section displaying warnings:

```
Push Triggers

Select which events should trigger sending a push notification to users.

Warning: in_array() expects parameter 2 to be array, boolean given in /var/www/html/wp-content/plugins/wp-web-push/wp-web-push-admin.php on line 343
/> When a post is published.
Warning: in_array() expects parameter 2 to be array, boolean given in /var/www/html/wp-content/plugins/wp-web-push/wp-web-push-admin.php on line 343
parent="new-post" /> When a post is updated.
Warning: in_array() expects parameter 2 to be array, boolean given in /var/www/html/wp-content/plugins/wp-web-push/wp-web-push-admin.php on line 343
/> Right after subscription (useful to show to users what notifications look like).

N.B.: You can override these options for individual posts when you create/edit them.
```

**Comment by mykmelez** [comment]
After pushing the updated image to https://wadi-pwa.sloppy.zone/, the first time I loaded that site, I saw the same error. It disappeared after a reload, however. And I don't see the "Push Triggers" warnings on that site.

**Comment by mykmelez** [comment]
Possibly related: the bell icon doesn't appear on https://wadi-pwa.sloppy.zone/, although it's there, as you see the pop-up message when you hover over where it should be. Also, Firefox complains that "parts of this page are not secure (such as images)."

**Comment by marco-c** [comment]
I've opened #269 for the mixed content issue.
I can't reproduce the warnings in the `Push Triggers` section.

I'll make this issue track the error with the bell.svg.
