### ISSUE TITLE
Add info about how to configure VAPID

### ISSUE THREAD

**Issue by a2sheppy** [mozilla/wp-web-push#309]
The configuration panel doesn't make it very clear exactly what's expected. Where does the key come from? Do you just make one using the usual openssl commands or do you get it from some tool or API somewhere? In general this isn't clear, and probably is even less so to less-technical users that just want push notifications for their blog.

**Comment by marco-c** [comment]
I will try to clarify the section.

**Comment by marco-c** [comment]
Maybe I'll hide the section by default and add a button to show it for advanced users.
