### ISSUE TITLE
Uncaught (in promise) DOMException: Registration failed - push service error

### ISSUE THREAD

**Issue by lukasag** [mozilla/wp-web-push#315]
Getting this on Chrome for Windows and Chrome for Android in latest versions of both browsers. It works normally on Firefox... Sometimes I also get another error together with it that I think it belongs to a function in your plugin..

undefined:1 Uncaught (in promise) DOMException: Registration failed - push service error
/wp-admin/admin-ajax.php?action=wpswmgr_serve&_wpswmanager=wpswmanager%2Fsw%2Fsw%40%2F:1 GET https://www.gameprosa.com.br/wp-admin/admin-ajax.php?action=wpswmgr_serve&_wpswmanager=wpswmanager%2Fsw%2Fsw%40%2F net::ERR_FILE_EXISTS

It's running on https://www.gameprosa.com.br
Everything is properly set, including GCM settings on my manifest.json file

**Comment by marco-c** [comment]
I've never seen this error, it could be somehow related to https://bugs.chromium.org/p/chromium/issues/detail?id=464365.

**Comment by marco-c** [comment]
Looks like you have two `<link rel="manifest"` in your page.
The plugin is adding `<link rel="manifest" href="https://www.gameprosa.com.br/wp-content/uploads/wpservefile_files/manifest.json">`.
Are you adding `<link rel="manifest" href="/manifest.json?v=kPPJxwmvjB">` manually?

**Comment by lukasag** [comment]
I didnt noticed your plugin adds a manifest. I have my own manifest file with my icons and web app settings. How about an option to disable the plugin generated manifest? I'll try disabling in the plugin code to see if the problem gets solved, I'll reply again within the next hours.

**Comment by marco-c** [comment]
You just need to comment out the line `$manifestGenerator = Mozilla\WebAppManifestGenerator::getInstance();` in wp-web-push-main.php.

If this fixes your problem, I'll add an option to disable the generation of the manifest.

**Comment by lukasag** [comment]
Marco, it did not fixed the problem.
Please check on https://www.gameprosa.com.br

Only one manifest file loading, still getting the **_"Uncaught (in promise) DOMException: Registration failed - push service error"_** error located at _undefined_, line 1. Unefined drives crazy, how can I properly debug this?

**Comment by marco-c** [comment]
The sender ID is usually a number, are you sure `gameprosa-1285` is correct?

**Comment by marco-c** [comment]
![image12](https://cloud.githubusercontent.com/assets/1616846/14705588/3238d1f4-07b2-11e6-8721-845300adda0f.png)

**Comment by lukasag** [comment]
My Dev. Console is different than yours. It does not have this content block and the overall design is pretty different. I've already tried to get to this same panel by going to this https://console.developers.google.com/home/dashboard URL but it always redirects me to https://console.developers.google.com/apis/
For this project the URL is https://console.developers.google.com/apis/library?project=gameprosa-1285
Even the page that shows all my projects is different and the only IDs it shows for my projects are like this one I am using.
Call me on Skype (lukasfire) if you want me to share my screen with you so you can see it, it's definitely weird.

**Comment by marco-c** [comment]
Try opening https://console.cloud.google.com/home/dashboard?project=gameprosa-1285&pli=1

**Comment by marco-c** [comment]
I filed https://github.com/google/WebFundamentals/issues/2847 to update the Google documentation.

**Comment by lukasag** [comment]
I fixed it, it was all my mistake. The page at Google Developer Console has another menu on the top-left corner where I didn't noticed a button to change from the API Manager to the Developer Console (which I tough i was already in because of the page name). The whole thing is confusing, you are inside a page with a name that is not that actual page but is part of it. Or I need to drink some less coffee and get into this "sleep 8 hours a day" routine.

The link you sent was also redirecting me to the API page. Now that I got to it from the menu I said, when I go back to the API page it shows me a buch of other links in this same menu that were not displaying before... (wtf Google! Really, WTF!?)

**Comment by lukasag** [comment]
Thanks Marco, sorry for wasting your time with this. The plugin is now working normally.
But the "enable manifest" button should be there because it will definitely cause problems to people who have their own manifest files. I also added a crossorigin="use-credentials" parameter to my manifest link.

**Comment by marco-c** [comment]
No worries, it was useful because I wouldn't have noticed that the documentation was outdated otherwise. Let's hope it's going to be fixed soon!

I'm going to file a new issue for the manifest thing.

**Comment by challenger532** [comment]
@lukasag hello, how did you solve it, I'm stuck with the same bug... wasted hours on that.. no result!
the same code is working on the browser, but when running with electron, I'm getting this bug...
