### ISSUE TITLE
Plugin Settings not properly updating.

### ISSUE THREAD

**Issue by lukasag** [mozilla/wp-web-push#317]
Changing "Title" and "GCM Project Number" fields had no effects on the plugin. It keeps using the old custom title I had set. The new settings were correctly saved to the Wordpress database.
#315 is the reason I had it changed (It's ok on my Manifest and set in the plugin page, but it's using the wrong parameters I had before.)

I just noticed this because I also changed the title when I placed the correct GCM Project Number and it did not updated in the "post-registration" notification.)
Only the welcome notification is working. Post update, new post and custom notifications keep using the wrong number.

**Comment by marco-c** [comment]
Are the options now correctly set if you open wp-admin/options-general.php?page=web-push-options ?

**Comment by lukasag** [comment]
It's working now. Why?
Yes they were correctly set. The "successfully subscribed" message was working normally after allowing the notifications from the browser to get the notifications, after updates or new posts the notifications were not firing.
I don't know why it's working now, but it wasn't about two minutes ago.
