### ISSUE TITLE
Update composer.json information

### ISSUE THREAD

**Issue by Mte90** [mozilla/wp-web-push#325]
The package name and dependence refer to the vendor marco-c but now is on github on mozilla vendor.
Can be fixed asap?

**Comment by marco-c** [comment]
Fatto: fcfde51.

Perché la fretta? 😄

**Comment by Mte90** [comment]
ahahah sto lavorando ad un boilerplate per plugin wordpress e volevo integrarlo però prima di rilasciare la nuova release c'é in pendenza questa libreria :-)

**Comment by Mte90** [comment]
As i can see there are many error when i try to add that package.
I have to add manually wp-swmanager, marco-c/wp-web-app-manifest-generator but lcobucci/jwt ask for a release that not exist.

**Comment by Mte90** [comment]
I get: `mozilla/wp-web-push 1.4.0 requires lcobucci/jwt dev-3.1-relaxed -> no matching package found.` and this package version not exist on github neither on packagist so i can't download that package :-(

**Comment by Mte90** [comment]
I tried with aliases and extra to replace the version of that package without success :-/
The only way is to update the version here.
