### ISSUE TITLE
archive project

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wp-web-push#337]
I think it's safe to say that this project is abandoned, and it should be archived. I'll do that after updating the description and readme.

@marco-c Perhaps you should also archive/remove its [listing in the WordPress Plugin Directory](https://wordpress.org/plugins/web-push/).

**Comment by mykmelez** [comment]
I've updated the description and readme. I'll wait to archive it in case @marco-c or others want to discuss archival/removal of the WordPress Plugin Directory listing.

**Comment by marco-c** [comment]
@mykmelez I was on vacation and I've just seen this, I agree with archiving. Should we also archive serviceworker-cookbook? We still receive issue reports so people are using it, but we have no one maintaining it (it could suddenly break and nobody would fix it).

**Comment by marco-c** [comment]
I will keep the plugin up as it still works with older versions of WordPress, but I expect usage to reduce as people update to new WordPress versions.

**Comment by mykmelez** [comment]
> @mykmelez I was on vacation and I've just seen this, I agree with archiving. Should we also archive serviceworker-cookbook? We still receive issue reports so people are using it, but we have no one maintaining it (it could suddenly break and nobody would fix it).

Yes, I think we should archive that one as well, as it sends the right message to folks who are using it (i.e. that we aren't maintaining it, and their issues won't be addressed).

**Comment by mykmelez** [comment]
> I will keep the plugin up as it still works with older versions of WordPress, but I expect usage to reduce as people update to new WordPress versions.

Ok, that's fine. I'll go ahead and archive this repository, then.
