### ISSUE TITLE
Don't prompt the user to subscribe again if he's denied the permission (or removed it from the prefs)

### ISSUE THREAD

**Issue by marco-c** [mozilla/wp-web-push#34]

**Comment by darkwing** [comment]
Ahh yes, receiving this in chrome:

`Uncaught (in promise) DOMException: Registration failed - no sender id provided`

**Comment by marco-c** [comment]
You need to set the GCM API key and sender ID in the options. I'll give you mine on IRC.

**Comment by darkwing** [comment]
Right; I reported that because if we don't have sufficient settings within admin, we shouldn't load anything on the front end.

**Comment by marco-c** [comment]
Maybe we should add a warning in the admin pages to tell the user that he needs to set the GCM specific options.

**Comment by marco-c** [comment]
There's no way to do this in Firefox currently because of:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1012167
- https://bugzilla.mozilla.org/show_bug.cgi?id=1242614
- pushsubscriptionchange isn't being triggered when the user removes the permission from the prefs

**Comment by marco-c** [comment]
Well, we could store a value in IndexedDB when the user approves the permission, then on page load we can check if the permission is 'granted' or 'prompt'. If it is 'prompt' and we have the value in the DB, then the user has removed the permission.

**Comment by marco-c** [comment]
I forgot, there's https://developer.mozilla.org/en-US/docs/Web/API/Notification/permission.

**Comment by marco-c** [comment]
This was fixed when I fixed #68.
