### ISSUE TITLE
Add a warning in the admin pages to remind the user to set the GCM specific options

### ISSUE THREAD

**Issue by marco-c** [mozilla/wp-web-push#45]

**Comment by darkwing** [comment]
We should also prevent the `wp_head` stuff from being included if we don't have the necessary info.

**Comment by marco-c** [comment]
Something like what Akismet does would be nice:
![warning](https://cloud.githubusercontent.com/assets/1616846/12485689/58abf958-c057-11e5-9d47-7cb6682defec.png)
