### ISSUE TITLE
Add some screenshots to the readme.txt file

### ISSUE THREAD

**Issue by marco-c** [mozilla/wp-web-push#55]
- [x] Prompt from Firefox
- [x] Prompt from Chrome on Android
- [x] Notification from Firefox on Linux
- [x] Notification from Firefox on Windows
- [x] Notification from Firefox on Mac
- [x] Notification from Chrome on Android
- [x] Dashboard

**Comment by TimAbraldes** [comment]
A couple options for consideration.

Firefox consent notification:
<img width="403" alt="firefox consent notification" src="https://cloud.githubusercontent.com/assets/955084/12733861/11e9ddc0-c8f2-11e5-9d4b-34a6bfdf5065.png">

Plugin activation:
<img width="184" alt="activate plugin" src="https://cloud.githubusercontent.com/assets/955084/12733862/146c9010-c8f2-11e5-8cc6-0b4a3c27b535.png">

**Comment by marco-c** [comment]
I wouldn't add the `Plugin activation` image because it's simply standard for WordPress (so people already know what it looks like and what it means).

I'd add the Firefox/Chrome prompts and a notification example. Maybe also the analytics from the widget in the dashboard, once we make it nicer.

**Comment by TimAbraldes** [comment]
<img width="325" alt="macnotification" src="https://cloud.githubusercontent.com/assets/955084/13087546/5538c59e-d49d-11e5-8301-1d9f48150ca7.png">

Mac notification

**Comment by TimAbraldes** [comment]
<img width="499" alt="dashboard" src="https://cloud.githubusercontent.com/assets/955084/13087611/a48ee4c0-d49d-11e5-8e95-5c61e1decf5d.png">

Dashboard

**Comment by marco-c** [comment]
> Dashboard

The dashboard should be more detailed now, maybe you have a older version of the plugin?

**Comment by TimAbraldes** [comment]
> The dashboard should be more detailed now, maybe you have a older version of the plugin?

I'm using this - https://github.com/mykmelez/wordpress-pwa - is it not up to date?

**Comment by marco-c** [comment]
> I'm using this - https://github.com/mykmelez/wordpress-pwa - is it not up to date?

It isn't updated to the latest commit, but it's using a version of the plugin that should contain the new dashboard widget.

**Comment by mykmelez** [comment]
I updated https://github.com/mykmelez/wordpress-pwa yesterday and will update it again today, but note that you can also do so yourself for testing an updated version of wp-web-push locally:

```
> git clone --recursive https://github.com/mykmelez/wordpress-pwa
Cloning into 'wordpress-pwa'...
remote: Counting objects: 64, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 64 (delta 30), reused 62 (delta 28), pack-reused 0
Unpacking objects: 100% (64/64), done.
Checking connectivity... done.
Submodule 'wp-web-push' (https://github.com/marco-c/wp-web-push.git) registered for path 'wp-web-push'
Cloning into 'wp-web-push'...
remote: Counting objects: 1097, done.
remote: Total 1097 (delta 0), reused 0 (delta 0), pack-reused 1097
Receiving objects: 100% (1097/1097), 188.58 KiB | 26.00 KiB/s, done.
Resolving deltas: 100% (680/680), done.
Checking connectivity... done.
Submodule path 'wp-web-push': checked out 'ac08651973efbca152c2a533734a9f6178caf107'
> cd wordpress-pwa/wp-web-push/
> git pull origin master
From https://github.com/marco-c/wp-web-push
 * branch            master     -> FETCH_HEAD
Updating ac08651..cfb2058
Fast-forward
 .travis.yml                           |  2 --
 Makefile                              | 22 +++++++++++++---------
 package.json                          |  2 +-
 version-changelog.js                  | 37 ++++++++++++++++++++++++++++++++-----
 wp-web-push/lang/web-push.pot         |  6 +++---
 wp-web-push/lib/js/Chart.min.js       | 11 -----------
 wp-web-push/lib/js/dashboard-chart.js |  1 +
 wp-web-push/lib/js/localforage.min.js |  7 -------
 wp-web-push/lib/js/options-page.js    | 22 ++++++++++++++++++++++
 wp-web-push/readme.txt                |  4 ++++
 wp-web-push/wp-web-push-admin.php     | 28 ++++++++++++++++------------
 wp-web-push/wp-web-push-main.php      | 35 ++++++++++++++++++++++++++---------
 wp-web-push/wp-web-push.php           |  2 +-
 13 files changed, 119 insertions(+), 60 deletions(-)
 delete mode 100644 wp-web-push/lib/js/Chart.min.js
 delete mode 100644 wp-web-push/lib/js/localforage.min.js
```

**Comment by TimAbraldes** [comment]
@mykmelez is there any step required between what you've written and `docker-compose` up?

**Comment by mykmelez** [comment]
> @mykmelez is there any step required between what you've written and docker-compose up?

Yes! You first have to `docker-compose build` to rebuild the image. (Unsure why `docker-compose up` doesn't do this automatically or at least warn you that the image is out-of-date.) You may also have to `docker-machine start <name of machine>` if it isn't already running (but `docker-compose up` will tell you if you have to do this).

**Comment by mykmelez** [comment]
@TimAbraldes also note https://github.com/mykmelez/wordpress-pwa/pull/4, which you'll probably need in order to build successfully.

**Comment by TimAbraldes** [comment]
I did this:

```
cd wp-web-push
git pull
cd ..
git checkout remove_composer_npm_install
docker-compose build
docker-compose up
```

but I'm still seeing the exact same dashboard. Maybe someone else can grab that screenshot?

**Comment by marco-c** [comment]
> Mac notification

@TimAbraldes maybe we should show a screenshot of the entire screen or at least a bigger part? Otherwise users won't understand what a notification is.

> but I'm still seeing the exact same dashboard. Maybe someone else can grab that screenshot?

I'll take the screenshot.
Anyway, I'm seeing the new dashboard on https://wadi-pwa.sloppy.zone/, so the current version of the plugin in myk's repo is updated enough.
I'm not sure what's going wrong in your case, but when I didn't know that `docker-compose build` existed, I completely removed the image with `docker rmi` and rebuilt it from scratch. Ugly solution, but it's guaranteed to work.

**Comment by TimAbraldes** [comment]
> > Mac notification
> 
> @TimAbraldes maybe we should show a screenshot of the entire screen or at least a bigger part? Otherwise users won't understand what a notification is.

Good point. Created this:

<img width="486" alt="macnotification" src="https://cloud.githubusercontent.com/assets/955084/13094179/f8415006-d4bd-11e5-84fa-5c4c39a90009.png">

**Comment by marco-c** [comment]
I've added the prompt and the notification images: https://wordpress.org/plugins/web-push/screenshots/

The OneSignal and GoRoost ones are nicer though, probably because they take the entire screen: https://wordpress.org/plugins/onesignal-free-web-push-notifications/screenshots/
https://wordpress.org/plugins/roost-for-bloggers/screenshots/

Our prompt screenshot in particular is a little hard to understand.

We should also take them from https://wadi-pwa.sloppy.zone/ so that a domain name shows up instead of an IP address.

**Comment by TimAbraldes** [comment]
<img width="1440" alt="firefoxprompt" src="https://cloud.githubusercontent.com/assets/955084/13118551/885b268a-d559-11e5-9dd9-52915ec566b9.png">

Better prompt image. Can I get the admin creds for the sloppy site so that I can post and take a screenshot of the resulting notification?

**Comment by mykmelez** [comment]
> Better prompt image. Can I get the admin creds for the sloppy site so that I can post and take a screenshot of the resulting notification?

Yes, I've emailed them to you!

**Comment by TimAbraldes** [comment]
<img width="1440" alt="firefoxnotification" src="https://cloud.githubusercontent.com/assets/955084/13120081/f9fa16dc-d560-11e5-8285-73e1dde692c9.png">

Better Firefox notification image

**Comment by TimAbraldes** [comment]
@marco-c let me know if there's anything else you'd like me to do here!

**Comment by marco-c** [comment]
@TimAbraldes I've listed the needed screenshots in the first comment. Let me know which ones you want to take and I'll take the remaining ones.

**Comment by TimAbraldes** [comment]
![chromemobileprompt](https://cloud.githubusercontent.com/assets/955084/13123020/da638fac-d56e-11e5-898f-7e4dad79619b.png)

Chrome mobile prompt

**Comment by TimAbraldes** [comment]
@marco-c OK I've taken the screenshots that I can: I don't have Linux or Windows, the dashboard shows up incorrectly for me on the sloppy instance, and I couldn't get a notification to go through to my mobile chrome (probably we're not signed up for GCM?). Hope the screenshots I took are hepful!

**Comment by marco-c** [comment]
Yes, looks like GCM on the wadi-pwa instance isn't configured (currently I can't get a notification on Chrome while using the wadi-pwa instance, but I can using my localhost server).

**Comment by marco-c** [comment]
Just three missing. I can't take the one on Linux at the moment because there's a bug in Firefox which makes notifications appear in the middle of the screen on HiDPI displays.

**Comment by marco-c** [comment]
Windows: #211 and http://plugins.trac.wordpress.org/changeset/1363677.

**Comment by marco-c** [comment]
Linux: #212 and http://plugins.trac.wordpress.org/changeset/1363970.
