### ISSUE TITLE
reference complete/accurate docs on configuring GCM

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wp-web-push#88]
The settings page says to follow the instructions on https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API#Extra_steps_for_Chrome_support to configure GCM, but those instructions are incomplete, since they tell you to make note of your API key, but they don't mention that you have to create that key (nor what kind of key it should be). We should reference complete (and accurate) docs or create them ourselves.

**Comment by marco-c** [comment]
We can use this: https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-04
Hopefully they'll keep it updated.
