### ISSUE TITLE
close Chrome/desktop notification on click

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wp-web-push#93]
After clicking on a notification, the notification disappears in Firefox/desktop, but it remains visible in Chrome/desktop. It seems like it should disappear in both cases. [This StackOverflow question](http://stackoverflow.com/questions/35100759/serviceworkers-focus-tab-clients-is-empty-on-notificationclick) suggests that "Android doesn't automatically close notifications on click" (where "Android" is presumably Chrome/Android), so I wonder if the workaround for Chrome/desktop is the same: to call `event.notification.close()`.

**Comment by marco-c** [comment]
Yes, I think it should be as simple as that.

**Comment by marco-c** [comment]
From MDN [1]: `some browsers close spawned notifications automatically, and some such as Chrome and Opera do not`.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Notification/close
