### ISSUE TITLE
Add icon and header to the Web Push plugin in the WordPress.org directory

### ISSUE THREAD

**Issue by marco-c** [mozilla/wp-web-push#98]
Currently there's a placeholder icon.

**Comment by marco-c** [comment]
We could ask on https://github.com/mozilla/Community-Design

**Comment by marco-c** [comment]
The last entry on https://wordpress.org/plugins/about/faq/ explains how to do it.

**Comment by marco-c** [comment]
@digitarald

**Comment by marco-c** [comment]
The icon is usually 128x128 on WordPress.org, can be PNG or SVG.

**Comment by digitarald** [comment]
Initial brainstorming using the classic bell:

![Bell v1](https://cldup.com/cewvn7KZQt.thumb.png)

Notification icon inspired by the classic chat:

![Chat 1](https://cldup.com/Uhabba0Ibd-3000x3000.png) ![Chat 2](https://cldup.com/psBl_rkqSa.thumb.png)

And mixing some more icons together without the extra circle, so they work better in smaller versions embedded into pages:

![Roundish](https://cldup.com/jzC9fj9GaJ-3000x3000.png)

**Comment by delapuente** [comment]
Another idea:
![push-icon-idea](https://cloud.githubusercontent.com/assets/757942/12913001/6f921ef8-cf1c-11e5-8d23-4cf6b8e56b75.png)

**Comment by marco-c** [comment]
Fixed by #150, I'll update the assets on WordPress.org shortly.

**Comment by marco-c** [comment]
Done: https://wordpress.org/plugins/web-push/.
